spring:
    application:
        name: api

    profiles:
        active: dev

jwt:
    secret: M2Y0YjU2YzgxYTA5M2RlZjU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNA==
    expiration: 900000  # 15 minutes

google:
    client-id: ${GOOGLE_CLIENT_ID}

refresh-token:
    expiration-days: 30