spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: never
management:
    endpoint:
        health:
            show-details: always
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        com.momentum.api.filter.RequestLoggingFilter: DEBUG