-- ============================================================
-- V1__init_schema.sql
-- Baseline schema for: User, RefreshToken, PasswordResetToken,
-- EmailVerificationToken, Exercise
-- ============================================================

-- ---------- users ----------
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL,
    password            VARCHAR(255),
    first_name          VARCHAR(255) NOT NULL,
    last_name           VARCHAR(255),
    picture_url         VARCHAR(500),
    idp                 VARCHAR(30)  NOT NULL,
    email_verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled             BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_locked  BOOLEAN      NOT NULL DEFAULT TRUE,
    role                VARCHAR(30)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_idp CHECK (idp IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT ck_users_role CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER'))
);

-- ---------- refresh_tokens ----------
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(500) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    family_id   VARCHAR(36)  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_family_id ON refresh_tokens (family_id);

-- ---------- password_reset_tokens ----------
CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_password_reset_tokens_token UNIQUE (token),
    CONSTRAINT fk_password_reset_tokens_user
       FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

-- ---------- email_verification_tokens ----------
CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_email_verification_tokens_token UNIQUE (token),
    CONSTRAINT fk_email_verification_tokens_user
       FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens (user_id);

-- ---------- exercises ----------
CREATE TABLE exercises (
    id            UUID        NOT NULL PRIMARY KEY,
    name          VARCHAR(50) NOT NULL,
    description   TEXT,
    muscle_group  VARCHAR(30) NOT NULL,
    equipment     VARCHAR(30) NOT NULL,
    difficulty    VARCHAR(20) NOT NULL,
    instructions  TEXT,
    video_url     VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_exercises_muscle_group CHECK (muscle_group IN (
         'CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS',
         'ABS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'FULL_BODY', 'CARDIO'
    )),
    CONSTRAINT ck_exercises_equipment CHECK (equipment IN (
        'BARBELL', 'DUMBBELL', 'KETTLEBELL', 'MACHINE', 'CABLE',
        'RESISTANCE_BAND', 'BODYWEIGHT', 'SMITH_MACHINE', 'MEDICINE_BALL', 'OTHER'
    )),
    CONSTRAINT ck_exercises_difficulty CHECK (difficulty IN (
        'BEGINNER', 'INTERMEDIATE', 'ADVANCED'
    ))
);

CREATE INDEX idx_exercise_muscle_group ON exercises (muscle_group);
CREATE INDEX idx_exercise_equipment ON exercises (equipment);
CREATE INDEX idx_exercise_difficulty ON exercises (difficulty);